services:
  backendchallenge.api:
    image: ${DOCKER_REGISTRY-}backendchallengeapi
    build:
      context: .
      dockerfile: BackendChallenge.API/Dockerfile

  backendchallenge.worker:
    image: ${DOCKER_REGISTRY-}backendchallengeworker
    build:
      context: .
      dockerfile: BackendChallenge.Worker/Dockerfile

